instance_data_dir: "datasets/j-small"
output_dir: "logs"
pretrained_model_name_or_path: "CompVis/stable-diffusion-v1-4"
val_prompts: val_prompts.txt
instance_str: sks
class_str: person
instance_prompt: "a photo of ${instance_str} ${class_str}"
class_data_dir: "datasets/person-class"
class_prompt: "a photo of ${class_str}"
resolution: 512
train_batch_size: 2
gradient_accumulation_steps: 1
lr_scheduler: "constant"
learning_rate: 1e-6
lr_warmup_steps: 0
max_train_steps: 2000
with_prior_preservation: true
prior_loss_weight: 1.0
train_text_encoder: true
revision: null
tokenizer_name: null
num_class_images: 200
seed: null
center_crop: false # else random crop
sample_batch_size: 4
gradient_checkpointing: false
use_8bit_adam: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1.0e-2
adam_epsilon: 1.0e-8
max_grad_norm: 1.0
clip_grad: true
mixed_precision: "no"
learnable_embedding: false
embedding_lr: 1e-4
limit_timesteps_lo: null
limit_timesteps_hi: null
augs: null # hflip, multi
text_encoder_lr: ${learning_rate}
text_encoder_max_steps: null